/***************************************************************************************************
Project :   Mercedes-Benz Vehicle Analytics
Task    :   Create RAW Tables
Day     :   3
Purpose :   Create RAW Tables, Stage, File Format and Load CSV (preserve what came from the source).
***************************************************************************************************/
USE ROLE MERC_DE;

ALTER SESSION SET QUERY_TAG =
'{"project":"mercedes","task":"create_raw_tables","day":"3"}';

USE WAREHOUSE LOAD_WH;
USE DATABASE MERCEDES_DEV;
USE SCHEMA RAW;


-- 1. CREATE USED CAR RAW TABLE

CREATE TABLE IF NOT EXISTS USED_CAR_RAW (
    MODEL           VARCHAR,
    YEAR            NUMBER,
    PRICE           NUMBER,
    TRANSMISSION    VARCHAR,
    MILEAGE         NUMBER,
    FUEL_TYPE       VARCHAR,
    TAX             NUMBER,
    MPG             FLOAT,
    ENGINE_SIZE     FLOAT
);


-- 2. CREATE FILE FORMAT

CREATE FILE FORMAT IF NOT EXISTS CSV_FORMAT
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null', '');


-- 3. CREATE INTERNAL STAGE FOR USED CAR STAGE

CREATE STAGE IF NOT EXISTS USED_CAR_STAGE
    FILE_FORMAT = CSV_FORMAT;

-- Check if the ingestion landing area actually receive the source files
LIST @MERCEDES_DEV.RAW.USED_CAR_STAGE;


-- 4. AFTER UPLOADING USED CAR CSV, LOAD IT
-- Don't include COPY INTO MANUFACTURING_RAW yet

COPY INTO MERCEDES_DEV.RAW.USED_CAR_RAW
FROM @MERCEDES_DEV.RAW.USED_CAR_STAGE
FILE_FORMAT = (
    FORMAT_NAME = MERCEDES_DEV.RAW.CSV_FORMAT
)
ON_ERROR = 'ABORT_STATEMENT';


-- 5. VALIDATE USED CAR DATA

SELECT COUNT(*) AS ROW_COUNT        -- 13119
FROM MERCEDES_DEV.RAW.USED_CAR_RAW;

SELECT *
FROM MERCEDES_DEV.RAW.USED_CAR_RAW
LIMIT 10;

SELECT
    COUNT(*)                AS TOTAL_ROWS,  -- 13119
    COUNT_IF(MODEL IS NULL) AS NULL_MODEL,  -- 0
    COUNT_IF(PRICE IS NULL) AS NULL_PRICE,  -- 0
    COUNT_IF(YEAR IS NULL)  AS NULL_YEAR    -- 0
FROM MERCEDES_DEV.RAW.USED_CAR_RAW;


-- 6. CREATE FILE FORMAT FOR MANUFACTURING SCHEMA INFERENCE
-- Used only by INFER_SCHEMA()
-- PARSE_HEADER tells Snowflake that the first row contains column names

CREATE FILE FORMAT IF NOT EXISTS MERCEDES_DEV.RAW.MANUFACTURING_INFER_FORMAT
    TYPE = CSV
    PARSE_HEADER = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';


-- 7. CREATE FILE FORMAT FOR MANUFACTURING DATA LOADING
-- Used by COPY INTO
-- SKIP_HEADER skips the CSV header when loading rows

CREATE FILE FORMAT IF NOT EXISTS MERCEDES_DEV.RAW.MANUFACTURING_LOAD_FORMAT
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null', '');


-- 8. CREATE INTERNAL STAGE FOR MANUFACTURING STAGE
-- The stage doesn't need to have the inference file format attached.

CREATE STAGE IF NOT EXISTS MANUFACTURING_STAGE
    FILE_FORMAT = MANUFACTURING_INFER_FORMAT;

-- Check that train.csv is in the stage
LIST @MERCEDES_DEV.RAW.MANUFACTURING_STAGE;


-- 9. INFER THE MANUFACTURING TABLE STRUCTURE

SELECT *
FROM TABLE(
    INFER_SCHEMA(
        LOCATION => '@MERCEDES_DEV.RAW.MANUFACTURING_STAGE',
        FILE_FORMAT => 'MERCEDES_DEV.RAW.MANUFACTURING_INFER_FORMAT'
    )
);


-- 10. CREATE MANUFACTURING RAW TABLE

CREATE TABLE IF NOT EXISTS MERCEDES_DEV.RAW.MANUFACTURING_RAW
USING TEMPLATE (
    SELECT ARRAY_AGG(
        OBJECT_CONSTRUCT(
            'COLUMN_NAME', COLUMN_NAME,
            'TYPE', TYPE,
            'NULLABLE', TRUE
        )
    )
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION => '@MERCEDES_DEV.RAW.MANUFACTURING_STAGE',
            FILE_FORMAT => 'MERCEDES_DEV.RAW.MANUFACTURING_INFER_FORMAT' -- use infer file format
        )
    )
);

-- Check the generated table structure

DESC TABLE MERCEDES_DEV.RAW.MANUFACTURING_RAW;  -- 378 columns header


-- 11. LOAD THE DATA INTO MANUFACTURING RAW TABLE

COPY INTO MERCEDES_DEV.RAW.MANUFACTURING_RAW
FROM @MERCEDES_DEV.RAW.MANUFACTURING_STAGE
FILE_FORMAT = (
    FORMAT_NAME = MERCEDES_DEV.RAW.MANUFACTURING_LOAD_FORMAT  -- use this file format for LOAD DATA (SKIP_HEADER = 1)
)
ON_ERROR = 'ABORT_STATEMENT';


-- 12. VALIDATE MANUFACTURING DATA

SELECT COUNT(*) AS ROW_COUNT        -- 4209
FROM MERCEDES_DEV.RAW.MANUFACTURING_RAW;

SELECT *
FROM MERCEDES_DEV.RAW.MANUFACTURING_RAW
LIMIT 10;