/***************************************************************************************************
Project : Mercedes-Benz Vehicle Analytics
Task    : NHTSA RAW ingestion
Day     : 3
Purpose : Store NHTSA API response in RAW layer
***************************************************************************************************/

USE ROLE MERC_DE;

ALTER SESSION SET QUERY_TAG =
'{"project":"mercedes","task":"nhtsa_raw_ingestion","day":"3"}';

USE WAREHOUSE LOAD_WH;
USE DATABASE MERCEDES_DEV;
USE SCHEMA RAW;


--  1. CREATE RAW TABLE

CREATE TABLE IF NOT EXISTS VEHICLE_SAFETY_RAW (
    SOURCE_FILE     VARCHAR,
    INGESTED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    API_RESPONSE    VARIANT
);

-- VALIDATE TABLE

DESC TABLE VEHICLE_SAFETY_RAW;


-- 2. CREATE JSON FILE FORMAT

CREATE FILE FORMAT IF NOT EXISTS NHTSA_JSON_FORMAT
    TYPE = JSON;


-- 3. CREATE STAGE

CREATE STAGE IF NOT EXISTS NHTSA_STAGE
    FILE_FORMAT = NHTSA_JSON_FORMAT;

-- 4. CHECK STAGE

LIST @MERCEDES_DEV.RAW.NHTSA_STAGE;


-- 5. LOAD JSON INTO VEHICLE_SAFETY_RAW TABLE

COPY INTO MERCEDES_DEV.RAW.VEHICLE_SAFETY_RAW
(
    SOURCE_FILE,
    API_RESPONSE
)
FROM (
    SELECT
        METADATA$FILENAME,          -- return provenance filename
        $1                          -- return API_RESPONSE (first value read)
    FROM @MERCEDES_DEV.RAW.NHTSA_STAGE
)
FILE_FORMAT = (
    FORMAT_NAME = MERCEDES_DEV.RAW.NHTSA_JSON_FORMAT
)
ON_ERROR = 'ABORT_STATEMENT';   -- stop COPY operation if encounter error loading the file


-- 6. VALIDATE VEHICLE SAFETY DATA

SELECT 
    COUNT(*) AS API_RESPONSES       -- 2 (2018.json and 2019.json)
FROM MERCEDES_DEV.RAW.VEHICLE_SAFETY_RAW;


SELECT
    SOURCE_FILE,
    INGESTED_AT,
    API_RESPONSE
FROM MERCEDES_DEV.RAW.VEHICLE_SAFETY_RAW
LIMIT 5;


-- 7. INSPECT JSON RESPONSE

SELECT 
    API_RESPONSE:"Count"::NUMBER AS API_COUNT  -- 26, 28
FROM MERCEDES_DEV.RAW.VEHICLE_SAFETY_RAW;


-- 8. FLATTEN RESULTS ARRAY 

SELECT 
    value
FROM MERCEDES_DEV.RAW.VEHICLE_SAFETY_RAW,
LATERAL FLATTEN(
    INPUT => API_RESPONSE:"Results"     -- Results is an array
)
LIMIT 10;