import os
from pathlib import Path
import snowflake.connector


# PROJECT CONFIGURATION

BASE_DIR = Path(__file__).resolve().parents[1]

# Directory containing JSON files generated by
# scripts/01_ingest_nhtsa.py
NHTSA_DIR = BASE_DIR / "data" / "raw" / "nhtsa"


# ENVIRONMENT CONFIGURATION

SNOWFLAKE_DATABASE = os.environ["SNOWFLAKE_DATABASE"]
SNOWFLAKE_ROLE = os.environ["SNOWFLAKE_ROLE"]

RAW_SCHEMA = "RAW"

NHTSA_STAGE = (
    f"{SNOWFLAKE_DATABASE}.{RAW_SCHEMA}.NHTSA_STAGE"
)

NHTSA_RAW_TABLE = (
    f"{SNOWFLAKE_DATABASE}.{RAW_SCHEMA}.VEHICLE_SAFETY_RAW"
)

NHTSA_JSON_FORMAT = (
    f"{SNOWFLAKE_DATABASE}.{RAW_SCHEMA}.NHTSA_JSON_FORMAT"
)


# MAIN

def main():

    print("=" * 70)
    print("LOADING NHTSA JSON INTO SNOWFLAKE")
    print("=" * 70)


    # 1. FIND GENERATED JSON FILES

    json_files = sorted(
        NHTSA_DIR.glob("nhtsa_safety_*.json")
    )

    if not json_files:

        raise FileNotFoundError(
            "No NHTSA JSON files found in "
            f"{NHTSA_DIR}"
        )

    print(
        f"\nJSON files found: {len(json_files)}"
    )

    for file in json_files:
        print(f"  - {file.name}")


    # 2. CONNECT TO SNOWFLAKE USING GITHUB ACTIONS SECRETS 

    conn = snowflake.connector.connect(
        account=os.environ["SNOWFLAKE_ACCOUNT"],
        user=os.environ["SNOWFLAKE_USER"],
        password=os.environ["SNOWFLAKE_PASSWORD"],
        warehouse="LOAD_WH",
        database=SNOWFLAKE_DATABASE,
        schema=RAW_SCHEMA,
        role=SNOWFLAKE_ROLE
    )

    cursor = conn.cursor()


    try:

        # 3. UPLOAD JSON FILES TO SNOWFLAKE INTERNAL STAGE

        for file in json_files:

            print(
                f"Uploading: {file.name}"
            )

            cursor.execute(
                f"""
                PUT
                'file://{file.as_posix()}'
                @{NHTSA_STAGE}
                AUTO_COMPRESS=FALSE
                OVERWRITE=FALSE
                """
            )


        # 4. COPY JSON INTO RAW TABLE
        #
        # FORCE=FALSE means Snowflake can use its normal
        # COPY load-history protection.
        #
        # Already-loaded files will not normally be loaded
        # again.

        print(
            "\nLoading staged JSON into "
            "{NHTSA_RAW_TABLE}..."
        )

        cursor.execute(
            """
            COPY INTO {NHTSA_RAW_TABLE}
            (
                SOURCE_FILE,
                API_RESPONSE
            )

            FROM (
                SELECT
                    METADATA$FILENAME,
                    $1
                FROM
                    @{NHTSA_STAGE}
            )

            FILE_FORMAT = (
                FORMAT_NAME =
                    '{NHTSA_JSON_FORMAT}'
            )

            ON_ERROR = 'ABORT_STATEMENT'

            FORCE = FALSE
            """
        )


        results = cursor.fetchall()

        print("\nCOPY INTO results:")

        for result in results:

            print(result)


        # 5. VALIDATE RAW TABLE

        cursor.execute(
            """
            SELECT COUNT(*)
            FROM {NHTSA_RAW_TABLE}
            """
        )

        row_count = cursor.fetchone()[0]

        print(
            f"\nRAW NHTSA rows: {row_count:,}"
        )


        print("\n" + "=" * 70)
        print(f"NHTSA RAW LOAD SUCCESS - {SNOWFLAKE_DATABASE}")
        print("=" * 70)


    finally:

        cursor.close()
        conn.close()



if __name__ == "__main__":
    main()