name: Mercedes CD

# CONTINUOUS DEPLOYMENT

# This workflow is intentionally NOT triggered automatically
# by every push.

# CI validates the code first.
# CD is manually triggered when we decide that the validated
# version is ready for production.

on:
  # Manual trigger from:
  # GitHub
  #   → Actions
  #   → Mercedes CD
  #   → Run workflow
    workflow_dispatch:

jobs:
    deploy-production: 

        # GitHub Environment
        # 'production' should be created in:
        # Repository
        # → Settings
        # → Environments
        # → production
        # This allows production-specific protection rules.
        
        environment: production
        runs-on: ubuntu-latest

        steps:
            
            # 1. DOWNLOAD REPOSITORY CODE
            - name: Checkout repository
              uses: actions/checkout@v4

            # 2. SET UP PYTHON
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            # 3. INSTALL PROJECT DEPENDENCIES
            - name: Install dependencies

              run: |
                python -m pip install --upgrade pip
                pip install -r ingestion/requirements.txt

            # 4. DEPLOY PRODUCTION SQL
            # SNOWFLAKE_DATABASE is deliberately set to
            # MERCEDES_PROD here.
            # This prevents the production deployment from
            # accidentally targeting MERCEDES_DEV.
            - name: Deploy Production
              env:
                SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                SNOWFLAKE_USER: ${{ vars.SNOWFLAKE_USER }}
                SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

                # Dedicated CI/CD SNOWFLAKE_ROLE
                SNOWFLAKE_ROLE: MERC_CI_CD

                SNOWFLAKE_WAREHOUSE: TRANSFORM_WH
                SNOWFLAKE_DATABASE: MERCEDES_PROD

              run: |
                python scripts/deploy_sql.py \
                    sql/deployment/02_deploy_prod.sql

            # 5. VALIDATE PRODUCTION DEPLOYMENT
            - name: Validate Production
              env:
                SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                SNOWFLAKE_USER: ${{ vars.SNOWFLAKE_USER }}
                SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

                SNOWFLAKE_ROLE: MERC_CI_CD
                
                SNOWFLAKE_WAREHOUSE: TRANSFORM_WH
                SNOWFLAKE_DATABASE: MERCEDES_PROD

              run: |
                python tests/test_snowflake_production.py

                            