/***************************************************************************************************       
Project :   Mercedes-Benz Vehicle Analytics
Task    :   Environment Setup   
Day     :   1
Purpose :   Create Snowflake foundation for data platform + governance
****************************************************************************************************/
USE ROLE ACCOUNTADMIN;

ALTER SESSION SET QUERY_TAG = '{"project":"mercedes","task":"environment_setup","day":"1"}';

-- 1. CREATE ROLES
CREATE ROLE IF NOT EXISTS MERC_DE;
CREATE ROLE IF NOT EXISTS MERC_ANALYST;

-- Role hierarchy
GRANT ROLE MERC_DE TO ROLE SYSADMIN;
GRANT ROLE MERC_ANALYST TO ROLE SYSADMIN;

-- Assign both personas to the user for testing
GRANT ROLE MERC_DE TO USER NABILA26;
GRANT ROLE MERC_ANALYST TO USER NABILA26;

-- 2. CREATE WAREHOUSES
--  Used for ingestion/loading
CREATE WAREHOUSE IF NOT EXISTS LOAD_WH
    WAREHOUSE_SIZE = 'XSMALL'
    WAREHOUSE_TYPE = 'STANDARD'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Used for transformations / Silver/ Gold/ Dynamic Tables
CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
    WAREHOUSE_SIZE = 'XSMALL'
    WAREHOUSE_TYPE = 'STANDARD'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- 3. WAREHOUSE ACCESS
GRANT USAGE ON WAREHOUSE LOAD_WH TO ROLE MERC_DE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE MERC_DE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE MERC_ANALYST;

-- 4. CREATE DATABASE
GRANT CREATE DATABASE ON ACCOUNT TO ROLE MERC_DE;

USE ROLE MERC_DE;
USE WAREHOUSE LOAD_WH;

CREATE DATABASE IF NOT EXISTS MERCEDES_DEV;
CREATE DATABASE IF NOT EXISTS MERCEDES_PROD;

-- 5. CREATE SCHEMAS - identical in both databases
CREATE SCHEMA IF NOT EXISTS MERCEDES_DEV.RAW;       -- raw, as-land
CREATE SCHEMA IF NOT EXISTS MERCEDES_DEV.SILVER;    -- cleaned, typed
CREATE SCHEMA IF NOT EXISTS MERCEDES_DEV.GOLD;      -- analytics-ready
CREATE SCHEMA IF NOT EXISTS MERCEDES_DEV.AUDIT;     -- dbt test failures land here

CREATE SCHEMA IF NOT EXISTS MERCEDES_PROD.RAW;
CREATE SCHEMA IF NOT EXISTS MERCEDES_PROD.SILVER;
CREATE SCHEMA IF NOT EXISTS MERCEDES_PROD.GOLD;
CREATE SCHEMA IF NOT EXISTS MERCEDES_PROD.AUDIT;

-- 6. GRANT ENGINEERING ACCESS
USE ROLE SYSADMIN;

GRANT ALL ON DATABASE MERCEDES_DEV TO ROLE MERC_DE;
GRANT ALL ON ALL SCHEMAS IN DATABASE MERCEDES_DEV TO ROLE MERC_DE;

GRANT ALL ON DATABASE MERCEDES_PROD TO ROLE MERC_DE;
GRANT ALL ON ALL SCHEMAS IN DATABASE MERCEDES_PROD TO ROLE MERC_DE;

-- 7. GRANT ANALYST READ-ONLY ACCESS -- PROD.GOLD only
GRANT USAGE ON DATABASE MERCEDES_PROD TO ROLE MERC_ANALYST;
GRANT USAGE ON SCHEMA MERCEDES_PROD.GOLD TO ROLE MERC_ANALYST;
GRANT SELECT ON ALL TABLES IN MERCEDES_PROD.GOLD TO ROLE MERC_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MERCEDES_PROD.GOLD TO ROLE MERC_ANALYST;

-- 8. RESOURCE MONITOR
USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS MERCEDES_PROJECT_MONITOR
    WITH CREDIT_QUOTA = 50
    FREQUENCY = NEVER
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS 
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO SUSPEND
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

-- 9. APPLY RESOURCE MONITOR TO BOTH WAREHOUSES
ALTER WAREHOUSE LOAD_WH SET RESOURCE_MONITOR = MERCEDES_PROJECT_MONITOR;
ALTER WAREHOUSE TRANSFORM_WH SET RESOURCE_MONITOR = MERCEDES_PROJECT_MONITOR;