/***************************************************************************************************
Project :   Mercedes-Benz Vehicle Analytics
Task    :   CI/CD Role Setup
Day     :   2
Purpose :   Create a dedicated deployment role for GitHub Actions
***************************************************************************************************/
USE ROLE ACCOUNTADMIN;

ALTER SESSION SET QUERY_TAG =
'{"project":"mercedes","task":"ci_cd_role_setup","day":"2"}';

-- 1. CREATE CI/CD ROLE
CREATE ROLE IF EXISTS MERC_CI_CD;

-- 2. ROLE HIERARCHY
GRANT ROLE MERC_CI_CD TO ROLE SYSADMIN;

-- 3. DEV ACCESS
GRANT USAGE DATABASE MERCEDES_DEV TO ROLE MERC_CI_CD;
GRANT ALL ON SCHEMA MERCEDES_DEV.RAW TO ROLE MERC_CI_CD;
GRANT ALL ON SCHEMA MERCEDES_DEV.SILVER TO ROLE MERC_CI_CD;
GRANT ALL ON SCHEMA MERCEDES_DEV.GOLD TO ROLE MERC_CI_CD;
GRANT ALL ON SCHEMA MERCEDES_DEV.AUDIT TO ROLE MERC_CI_CD;

-- 4. PROD ACCESS
GRANT USAGE ON DATABASE MERCEDES_PROD TO ROLE MERC_CI_CD;
GRANT ALL ON SCHEMA MERCEDES_PROD.RAW TO ROLE MERC_CI_CD;
GRANT ALL ON SCHEMA MERCEDES_PROD.SILVER TO ROLE MERC_CI_CD;
GRANT ALL ON SCHEMA MERCEDES_PROD.GOLD TO ROLE MERC_CI_CD;
GRANT ALL ON SCHEMA MERCEDES_PROD.AUDIT TO ROLE MERC_CI_CD;

-- 5. WAREHOUSE ACCESS
GRANT USAGE ON WAREHOUSE LOAD_WH TO ROLE MERC_CI_CD;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE MERC_CI_CD;